# Generated by Django 5.1.3 on 2024-11-10 16:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='autor',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='documento',
            name='fecha_subida',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='categoria',
            field=models.CharField(choices=[('fisica', 'Física'), ('quimica', 'Química'), ('biologia', 'Biología')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
